### PR TITLE
Update the header location to reflect the new API

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by superm1** [comment]
The other thing to check - is the GObject introspection still 1.0 ABI?  Or does that bump too?

**Comment by hughsie** [comment]
> Or does that bump too?

Good question, will do some tests.

**Comment by hughsie** [comment]
> will do some tests

It needs a bump too; I've added that as a follow up commit. Is this for Debian where both versions are parallel installable? If so, are there any other files that are conflicting?

**Comment by superm1** [comment]
>It needs a bump too; I've added that as a follow up commit. Is this for Debian where both versions are parallel installable? If so, are there any other files that are conflicting?

That gets the last that I see, thanks!

**Pull request merged**
