### PR TITLE
Hughsie/ancestor regression

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by hughsie** [comment]
I'm fuzzing this now, but so far so good.

**Comment by sidt4** [comment]
Thanks for the quick fix Hughsie.

Should we have a unit test for this fix ?

**Comment by hughsie** [comment]
> Should we have a unit test for this fix ?

That's probably a good idea. I think it's trying to handle a *lot* of deep children, so it's not a trivial thing to test.

**Comment by sidt4** [comment]
Maybe `appstream` (or other `libxmlb` clients) has tests which can test `libxmlb` in these non-trivial cases.

**Pull request merged**
