### PR TITLE
Convert the contents after decoding a GZipped file

### PR DESCRIPTION
**Pull request by robert-ancell**
Previously the contents were assumed to be XML, and this didn't work with GZip
compressed YAML.

The code isn't optimal as it writes decodes the GZipped file to a temporary
file. This was done because the converter API uses a GFile instead of a
GInputStream. The existing XML case doesn't use the temporary file so shouldn't
have a performance hit.

### CODE REVIEW

**Comment by robert-ancell** [comment]
https://github.com/hughsie/libxmlb/issues/13

**Comment by hughsie** [comment]
I tried to implement something a bit cleaner (i.e. using a GInputStream for the vfunc) but I couldn't get `g_file_input_stream_query_info()` to return the `G_FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE` -- only NULL for a valid stream of `<id>gimp</id>`.  Any tips? I tried seeking to the file start before checking but nothing.

**Comment by robert-ancell** [comment]
I also tried using `g_file_input_stream_query_info()` initially but looking at the glib source only `G_FILE_ATTRIBUTE_TIME_MODIFIED`, `G_FILE_ATTRIBUTE_TIME_MODIFIED_USEC`, and `G_FILE_ATTRIBUTE_STANDARD_NAME` are set (`gio/gzlibdecompressor.c` `g_zlib_decompressor_convert()`). So that's why I had to use `g_content_type_guess()`.

Note if you change the API to use `GInputStream` then you also need to pass the filename around. In the case of YAML the `g_content_type_guess()` doesn't work without checking for the extension.

**Comment by superm1** [comment]
Superseded by #15.  Feel free to leave any comments on it there.

**Pull request closed without merging**
