### PR TITLE
Include records in the symbol export list

### PR DESCRIPTION
**Pull request by hughsie**
This syncs with the fixed copy from fwupd.

### CODE REVIEW

**Comment by hughsie** [comment]
@pwithnall sanity check on the added symbols in the .map file please.

**Comment by ximion** [comment]
The quoting style change make this a bit hard to read, but the change makes sense to me! (did you format the code with Black? Looks a bit like that style!)

**Comment by hughsie** [comment]
Ya, black FTW.

**Review by pwithnall — APPROVED** [review]
Yeah, the quoting style change should probably be a separate commit so it can be ignored during review.

The map changes look OK to me ottomh

**Pull request merged**
